---

# ansible-playbook --ask-vault-pass node.yml -vvv

- hosts: localhost
  become: yes

  tasks: 
   - name: "Install git, nginx, nodejs, npm and python-pip"
     apt:
       name: "{{ item }}"
       state: installed
       update_cache: yes
     with_items:
       - git 
       - nginx
       - python-pip

   - name: Add nodesource apt key
     shell: curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -

   - name: Install the nodejs LTS repos
     apt_repository:
      repo: deb https://deb.nodesource.com/node_9.x {{ ansible_distribution_release }} main
      state: present
      update_cache: yes

   - name: Install nodejs and npm
     apt:
      pkg: "{{ item }}"
      state: present
      update_cache: true
     with_items:
       - nodejs
  #  - name: Install nodejs and npm
  #    apt:
  #      pkg: "{{ item }}"
  #      state: present
  #      update_cache: true
  #    with_items:
  #      - nodejs
  #      - npm
  #    ignore_errors: yes
   
   - name: Include vars from the vault
     include_vars:
       file: creds.yml
     no_log: true
   
   - name: Install the dependencies for aws.js
     command: npm install
     args:
       chdir: /home/vagrant/Project/Milestone4

   - name: Delete inventory and dns.json file
     file: 
       path: "{{ item }}"
       state: absent
     with_items:
       - inventory
       - dns.yml

   -  name: Run aws.js for Jenkins
      command: node aws.js Jenkins
      args:
        chdir:  /home/vagrant/Project/Milestone4
      environment:
        AWSAccessKeyId : "{{ AWSAccessKeyId }}"
        AWSSecretKey : "{{ AWSSecretKey }}"  
   
   - pause:
       seconds: 20

   - name: Refresh inventory
     meta: refresh_inventory
...     